#!/bin/sh
# Regenerates src/generated/contract.ts from the built contract.
# Run from sdk/ after `stellar contract build` in ../contracts.
set -eu
WASM=../contracts/target/wasm32v1-none/release/kepter.wasm
TMP=$(mktemp -d)
stellar contract bindings typescript --wasm "$WASM" --output-dir "$TMP/kepter-contract" --overwrite
{
  echo "// Generated by scripts/generate.sh from the Kepter contract. Do not edit by hand."
  # Node's type stripping cannot run parameter properties. The base Client
  # already stores options, so the property is dropped.
  # Imports that are only types are marked as such for the same reason.
  sed -e 's/constructor(public readonly options: ContractClientOptions)/constructor(options: ContractClientOptions)/' \
    -e 's/^  ClientOptions as ContractClientOptions,/  type ClientOptions as ContractClientOptions,/' \
    -e 's/^  MethodOptions,/  type MethodOptions,/' \
    -e 's/^  Result,/  type Result,/' \
    "$TMP/kepter-contract/src/index.ts"
} > src/generated/contract.ts
rm -r "$TMP"
